/* to clean up the database */
DROP SCHEMA IF EXISTS p02 CASCADE;
CREATE SCHEMA p02;
DROP TABLE IF EXISTS p02.customers CASCADE;
DROP TABLE IF EXISTS p02.locations  CASCADE;
DROP TABLE IF EXISTS p02.employees CASCADE;
DROP TABLE IF EXISTS p02.drivers CASCADE;
DROP TABLE IF EXISTS p02.carmodels CASCADE;
DROP TABLE IF EXISTS p02.cardetails CASCADE;
DROP TABLE IF EXISTS p02.assigns CASCADE;
DROP TABLE IF EXISTS p02.handover CASCADE;
DROP TABLE IF EXISTS p02.returne CASCADE;